//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AccessPoint
{
	private string ssid
	{
		get;
		set;
	}

	private string macAdresse
	{
		get;
		set;
	}

	private string verschluesselungstyp
	{
		get;
		set;
	}

	public AccessPoint()
	{
	}

}

