//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Benutzer
{
	private string nachname
	{
		get;
		set;
	}

	private string vorname
	{
		get;
		set;
	}

	private int person_id
	{
		get;
		set;
	}

	private bool gesperrt
	{
		get;
		set;
	}

}

